#!/usr/bin/python2
# -*- coding: utf-8 -*-
import json,sys,urllib,os
#TODO: Document code
#TODO: Abstract into functions (Is "__name__ == '__main__'" a thing in python2?)
#TODO: Add ability to specify other repos
#TODO: Store repo in directory and sync with it occassionally (maybe we can use a directory in /root?)
urllib.urlretrieve("https://repo.webosbrew.org/api/apps.json", "/tmp/repo.json")
repo = json.load(open("/tmp/repo.json"))
operation = sys.argv[1]
if operation == "help":
    print "help: Prints this help message (Usage: `hbpm help`)"
    print "list: Prints all available packages in the repo (Usage: `hbpm list`)"
    print "install: Installs package from repo by ID (Usage: `hbpm install $ipkId`)"
    print "remove: Removes installed application by ID (Usage: `hbpm remove $ipkId`)"
elif operation == "list":
    for package in repo["packages"]:
        print package["title"] + " - " + package["id"]
elif operation == "install":
    packageIdUser = sys.argv[2]
    for package in repo["packages"]:
        if package["id"] == packageIdUser:
            print "Installing " + package["title"]
            urllib.urlretrieve(package["manifestUrl"], "/tmp/manifest.json")
            manifest = json.load(open("/tmp/manifest.json"))
            version = manifest["version"]
            ipkUrl = package["manifestUrl"].replace(package["manifestUrl"].split("/")[len(package["manifestUrl"].split("/"))-1], "") + manifest["ipkUrl"]
            packageId = package["id"]
            #Assemble call to appInstallService/dev/install (This is probably slightly out of order of how makes sense, but ¯\_(ツ)_/¯)
            call = 'luna-send -n 1 -f luna://com.webos.appInstallService/dev/install \'{"id":"' + packageId + '","ipkUrl":"'+ "/tmp/app.ipk" + '","subscribe":true}\''
            urllib.urlretrieve(ipkUrl, "/tmp/app.ipk")
            os.system(call + "> /dev/null")
            print "Installed " + package["title"] + "!"
elif operation == "install-ipk":
    #args: hbpm install-ipk $ipkUrl $ipkId
    #install local ipk instead of reading from repo
    #TODO: make this an optional arg for normal install
    call = 'luna-send -n 1 -f luna://com.webos.appInstallService/dev/install \'{"id":"' + sys.argv[3] + '","ipkUrl":"'+ sys.argv[2] + '","subscribe":true}\''
elif operation == "remove":
    packageIdUser = sys.argv[2]
    call = 'luna-send -n 1 -f luna://com.webos.appInstallService/dev/remove \'{"id":"' + packageIdUser + '","subscribe":true}\''
    os.system(call + "> /dev/null")
elif operation == "cli":
    #Subset of commands for installing native/sh-based cli tools
    operation = sys.argv[2]
    urllib.urlretrieve("https://ruthenic.com/hbpm-cli-repo/apps.json", "/tmp/repo.json")
    repo = json.load(open("/tmp/repo.json"))
    if operation == "list":
        for package in repo["packages"]:
            print package["title"]
    elif operation == "install":
        packageIdUser = sys.argv[3]
        for package in repo["packages"]:
            if package["title"] == packageIdUser:
                print "Installing " + package["title"]
                urllib.urlretrieve(package["manifestUrl"], "/tmp/manifest.json")
                manifest = json.load(open("/tmp/manifest.json"))
                version = manifest["version"]
                ipkUrl = package["manifestUrl"].replace(package["manifestUrl"].split("/")[len(package["manifestUrl"].split("/"))-1], "") + manifest["ipkUrl"]
                urllib.urlretrieve(ipkUrl, "/media/internal/bin/" + manifest["ipkUrl"])
                os.system("chmod a+x /media/internal/bin/" + manifest["ipkUrl"])
                print "Installed " + package["title"] + "!"
    elif operation == "remove":
        os.system("rm -rf /media/internal/bin/" + sys.argv[3])
